apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-sample-app
  template:
    metadata:
      labels:
        app: devops-sample-app
    spec:
      containers:
      - name: devops-sample-app
        image: yourdockerhubusername/devops-sample-app:latest
        ports:
        - containerPort: 5000
